version: '3'

services:
  vue-app:
    build:
      context: ./front-end/ppro-coding-assignment
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - vue-cypress
    command: ["npm", "run", "serve"]  # Run the development server

  # Cypress service
  vue-cypress:
    image: cypress/base:14
    working_dir: /usr/src/app
    environment:
      - CYPRESS_CACHE_FOLDER=/root/.cache/Cypress
      - CYPRESS_RUN_BINARY=/root/.cache/Cypress/6.3.0/Cypress/Cypress
    volumes:
      - ./front-end/ppro-coding-assignment:/usr/src/app
    entrypoint: ["npm", "run", "test:e2e"]
    
  catalog-service:
    build:
      context: ./microservices/catalog-service
    ports:
      - "8001:80"
    depends_on:
      - database

  checkout-service:
    build:
      context: ./microservices/checkout-service
    ports:
      - "8002:80"
    depends_on:
      - database

  mail-service:
    build:
      context: ./microservices/mail-service
    ports:
      - "8003:80"
    depends_on:
      - database

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - vue-app
      - catalog-service
      - checkout-service
      - mail-service

  database:
    image: mysql:latest
    env_file: .env
    ports:
      - "3306:3306"
