version: '3'

services:
  catalog-service:
    build:
      context: ./catalog-service
    ports:
      - "8001:80"
    depends_on:
      - database

  database:
    image: mysql:latest
    env_file: .env
    environment:
      MYSQL_DATABASE: PurchasePRO_Coding_Assignment
      MYSQL_USER: root
    ports:
      - "3306:3306"
