version: '3'

services:
  catalog-service:
    build:
      context: ./catalog-service
    ports:
      - "8001:80"
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: PurchasePRO_Coding_Assignment
      MYSQL_USER: root
      MYSQL_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_ROOT_PASSWORD }}
    ports:
      - "3306:3306"
