# catalog-service/Dockerfile

FROM php:7.4-apache

WORKDIR /var/www/html

COPY . .

RUN chown -R www-data:www-data /var/www/html/storage \
    && chmod -R 775 /var/www/html/storage

RUN docker-php-ext-install pdo_mysql

EXPOSE 80
