name: Deploy to AWS EC2

on:
  pull_request:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/compose-cli@latest

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose push

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            PR_BRANCH=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
            git clone --branch "$PR_BRANCH" https://github.com/jplarida/PurchasePRO-Coding-Assignment.git ~/monorepo
            cd ~/monorepo
            docker-compose pull
            docker-compose up -d
