name: Deploy to AWS EC2

on:
  pull_request:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_ROOT_PASSWORD: ${{ secrets.DATABASE_ROOT_PASSWORD }}
      MYSQL_DATABASE: PurchasePRO_Coding_Assignment
      MYSQL_USER: root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print environment secrets
        run: |
          echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
          echo "DATABASE_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD" >> .env
          echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> .env
          echo "MYSQL_USER=$MYSQL_USER" >> .env

      - name: Set up Docker
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${{ github.workspace }}:/github/workspace -w /github/workspace \
            docker/compose up -d

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose push

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem
          ssh-keyscan -t rsa ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/ec2-key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "mkdir -p ~/monorepo"

      - name: Install Docker on EC2
        run: |
          ssh -i ~/.ssh/ec2-key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "sudo apt-get update && sudo apt-get install -y docker.io"


      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.2            
        with:
          host: ${{secrets.EC2_HOST}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          username: ${{secrets.EC2_USERNAME}}
          script: |
            if [ -d ~/monorepo ]; then rm -Rf ~/monorepo; fi
            mkdir -p ~/monorepo
            PR_BRANCH=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
            git clone git@github.com:jplarida/PurchasePRO-Coding-Assignment.git ~/monorepo
            cd ~/monorepo
            docker-compose pull
            docker-compose up -d